<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $moderator_id
 * @property string $created_at
 * @property string $forbidden_at
 * @property string $title
 * @property string $text
 * @property integer $status
 *
 * @property User $user
 */
class News extends \yii\db\ActiveRecord
{
    const NEWS_NEW = 0;
    const NEWS_ACTIVE = 1;
    const NEWS_BLOCK = 2;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'created_at', 'title', 'text', 'status'], 'required'],
            [['user_id', 'moderator_id', 'status'], 'integer'],
            [['created_at', 'forbidden_at'], 'safe'],
            [['text'], 'string', 'max' => 5000],
            [['title'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'moderator_id' => Yii::t('app', 'Moderator ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'forbidden_at' => Yii::t('app', 'Forbidden At'),
            'title' => Yii::t('app', 'Title'),
            'text' => Yii::t('app', 'Text'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    private function getDataDefaul()
    {
        $this->moderator_id = $this->user_id = Yii::$app->user->identity->id;
        $this->status = self::NEWS_ACTIVE;
        $this->created_at = $this->forbidden_at = date('Y-m-d H:m:i', strtotime('now'));

    }
    public function save($runValidation = true, $attributeNames = null)
    {
        $this->getDataDefaul();

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
    public function getProvider()
    {
        $query = self::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);
        return $dataProvider;
    }
}
